config/routes.rb
Rails.application.routes.draw do
  resources :utilisateurs
  devise_for :users
  root 'pages#home'
  get 'about'   => 'pages#about'
  get 'contact' => 'pages#contact'
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
end

app/models/utilisateur.rb
class Utilisateur < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	end
	def contact
	end
	def about
	end
end

app/controllers/utilisateurs_controller.rb
class UtilisateursController < ApplicationController
  before_action :set_utilisateur, only: [:show, :edit, :update, :destroy]
  #before_action :authenticate_user!

  # GET /utilisateurs
  # GET /utilisateurs.json
  def index
    @utilisateurs = Utilisateur.all
  end

  # GET /utilisateurs/1
  # GET /utilisateurs/1.json
  def show
  end

  # GET /utilisateurs/new
  def new
    @utilisateur = Utilisateur.new
  end

  # GET /utilisateurs/1/edit
  def edit
  end

  # POST /utilisateurs
  # POST /utilisateurs.json
  def create
    @utilisateur = Utilisateur.new(utilisateur_params)

    respond_to do |format|
      if @utilisateur.save
        format.html { redirect_to @utilisateur, notice: "l'Utilisateur a été créé avec succès." }
        format.json { render :show, status: :created, location: @utilisateur }
      else
        format.html { render :new }
        format.json { render json: @utilisateur.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /utilisateurs/1
  # PATCH/PUT /utilisateurs/1.json
  def update
    respond_to do |format|
      if @utilisateur.update(utilisateur_params)
        format.html { redirect_to @utilisateur, notice: "l'Utilisateur a correctement été mis à jour." }
        format.json { render :show, status: :ok, location: @utilisateur }
      else
        format.html { render :edit }
        format.json { render json: @utilisateur.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /utilisateurs/1
  # DELETE /utilisateurs/1.json
  def destroy
    @utilisateur.destroy
    respond_to do |format|
      format.html { redirect_to utilisateurs_url, notice: "l'Utilisateur a été supprimé." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_utilisateur
      @utilisateur = Utilisateur.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def utilisateur_params
      params.require(:utilisateur).permit(:nom, :prenom, :rue, :code_postal, :ville, :telephone, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper

  def devise_error_messages!
    flash_alerts = []
    error_key = 'errors.messages.not_saved'

    if !flash.empty?
      flash_alerts.push(flash[:error]) if flash[:error]
      flash_alerts.push(flash[:alert]) if flash[:alert]
      flash_alerts.push(flash[:notice]) if flash[:notice]
      error_key = 'devise.failure.invalid'
    end

    return "" if resource.errors.empty? && flash_alerts.empty?
    errors = resource.errors.empty? ? flash_alerts : resource.errors.full_messages

    messages = errors.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t(error_key, :count    => errors.count,
                                 :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation">
      <h2>#{sentence}</h2>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/utilisateurs_helper.rb
module UtilisateursHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mon appli</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'default', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= ui_bibz_meta_links%>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Brand</a>
      </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Accueil", root_path %></li>
        <li class="<%= 'active' if current_page?(about_path) %>"><%= link_to "A propos", about_path %></li>
			<li class="<%= 'active' if current_page?(contact_path) %>"><%= link_to "Contact", contact_path %></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Liste <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li class="<%= 'active' %>" role="presentation">
            <li><a href="/">Accueil</a></li>
            <li><a href="/about">A propos</a></li>
            <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Se connecter", new_user_session_path %></li>
            <li role="separator" class="divider"></li>
            <li><a href="/utilisateurs">Mes informations</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Mon tableau de bord</a></li>
          </ul>
        </li>
      </ul>
     	
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Rechercher">
        </div>
        <button type="submit" class="btn btn-default">Rechercher</button>
      </form>
      <ul class="nav navbar-nav navbar-right" id="bouton">
      	<li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Se connecter", new_user_session_path %></li>
        <li class="<%= 'active' if current_page?(about_path) %>"><%= link_to "S'enregistrer", new_user_registration_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
		
		<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<h1>A propos</h1>

app/views/pages/contact.html.erb
<h1>Contact</h1>

app/views/pages/home.html.erb
<h1>Bienvenue sur mon site</h1>

app/views/utilisateurs/_form.html.erb
<%= form_for(@utilisateur) do |f| %>
  <% if @utilisateur.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@utilisateur.errors.count, "error") %> prohibited this utilisateur from being saved:</h2>

      <ul>
      <% @utilisateur.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nom %><br>
    <%= f.text_field :nom %>
  </div>
  <div class="field">
    <%= f.label :prenom %><br>
    <%= f.text_field :prenom %>
  </div>
  <div class="field">
    <%= f.label :rue %><br>
    <%= f.text_field :rue %>
  </div>
  <div class="field">
    <%= f.label :code_postal %><br>
    <%= f.text_field :code_postal %>
  </div>
  <div class="field">
    <%= f.label :ville %><br>
    <%= f.text_field :ville %>
  </div>
  <div class="field">
    <%= f.label :telephone %><br>
    <%= f.text_field :telephone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/utilisateurs/edit.html.erb
<h1>Edition de l'Utilisateur</h1>

<%= render 'form' %>

<%= link_to 'Show', @utilisateur %> |
<%= link_to 'Retour', utilisateurs_path %>

app/views/utilisateurs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Liste des Utilisateurs</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>ID</th>
      <th>NOM</th>
      <th>PRENOM</th>
      <th>RUE</th>
      <th>CODE POSTAL</th>
      <th>VILLE</th>
      <th>TELEPHONE</th>
      <th>EMAIL</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @utilisateurs.each do |utilisateur| %>
      <tr>
        <td><%= utilisateur.id %></td>
        <td><%= utilisateur.nom %></td>
        <td><%= utilisateur.prenom %></td>
        <td><%= utilisateur.rue %></td>
        <td><%= utilisateur.code_postal %></td>
        <td><%= utilisateur.ville %></td>
        <td><%= utilisateur.telephone %></td>
        <td><%= utilisateur.email %></td>
        <td><%= link_to 'Voir', utilisateur %></td>
        <td><%= link_to 'Editer', edit_utilisateur_path(utilisateur) %></td>
        <td><%= link_to 'Supprimer', utilisateur, method: :delete, data: { confirm: 'Etes-vous sûr ?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'Nouvel Utilisateur', new_utilisateur_path %>

app/views/utilisateurs/new.html.erb
<h1>Création d'un Utilisateur</h1>

<%= render 'form' %>

<%= link_to 'Retour', utilisateurs_path %>

app/views/utilisateurs/show.html.erb
<p id="notice"><%= notice %></p>

<div class="informations">
   <p>
  <strong>ID :</strong>
  <%= @utilisateur.id %>
  </p>
  <p>
  <strong>Nom :</strong>
  <%= @utilisateur.nom %>
  </p>

  <p>
  <strong>Prénom :</strong>
  <%= @utilisateur.prenom %>
  </p>

  <p>
  <strong>Rue :</strong>
  <%= @utilisateur.rue %>
  </p>

  <p>
  <strong>Code postal :</strong>
  <%= @utilisateur.code_postal %>
  </p>

  <p>
  <strong>Ville :</strong>
  <%= @utilisateur.ville %>
  </p>

  <p>
  <strong>Telephone:</strong>
  <%= @utilisateur.telephone %>
  </p>

  <p>
  <strong>Email :</strong>
  <%= @utilisateur.email %>
  </p>
</div>

<%= link_to 'Editer', edit_utilisateur_path(@utilisateur) %>


<div class="btn btn-alert"
<%= link_to 'Retour', utilisateurs_path %>>
</div>